name: Build - Continuous

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Dependencies
        run: |
          go get .

      - name: Build
        run: |
          ./src/bin/build-scripts/build.sh

      - name: Copy Binary
        run: |
          mkdir -p release-bin/
          cp r2modman-headless release-bin/r2modman-headless-linux-amd64

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            release-bin/*