name: Build - Release

on:
  push:
    tags:
    - '!*'
    - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Dependencies
        run: |
          go get .

      - name: Build
        run: |
          ./src/bin/build-scripts/build.sh

      - name: Copy Binary
        run: |
          mkdir -p release-bin/
          cp r2modman-headless release-bin/r2modman-headless-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE
            release-bin/**
